# Amazinum home task 2 Dmytro Lutsyk Pandas

## Question 1

Usage:
  /Library/Developer/CommandLineTools/usr/bin/python3 -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --proxy <proxy>             Specify a proxy in the form
                              [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted,
                              even though it does not have valid or any HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If
                              provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation
                              for more information.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming
                              unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward
                              incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be
                              removed in the future.
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [3]:
def answer_one():
    '''Ця функція виконує читання 3-х датасетів, 
      препроцесинг, та повертає їх об'єднання'''

    
    energy = (pd
        .read_excel('Energy_Indicators.xls')
        .drop(['Unnamed: 0', 'Unnamed: 1'], axis=1)
        .replace('...', np.nan)
        .iloc[16:244]
        .reset_index(drop=True)
    )
    energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy['Energy Supply'] *= 1_000_000
    energy['Country'] = (energy['Country']
        .replace('[0-9]+', '', regex=True)
        .str.extract(r'^(.+?)(?:\s*\([^)]*\))?$')[0]
        .replace({'Republic of Korea'                                   : 'South Korea',
                  'United States of America'                            : 'United States',
                  'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
                  'China, Hong Kong Special Administrative Region'      : 'Hong Kong'
                 })
    )


    GDP = pd.read_csv('API_NY.GDP.MKTP.CD_DS2_en_csv_v2_133326.csv',  skiprows=3).rename(columns={'Country Name': 'Country'})
    GDP['Country'] = (GDP['Country']
        .replace({'Korea, Rep.'         : 'South Korea',
                  'Iran, Islamic Rep.'  : 'Iran',
                  'Hong Kong SAR, China': 'Hong Kong'})
    )
    GDP_merge_cols = ['Country'] + [str(year) for year in range(2006, 2016)] # Тільки колонки Country та list comprehension для років від 2006 до 2015
    

    ScimEn = (pd
        .read_excel('scimagojr_country_rank_1996-2024.xlsx')
        .drop('Region', axis=1) 
    )
    ScimEn_top15_rank = ScimEn[ScimEn['Rank'] <= 15]

    
    merged_dfs = (pd
        .merge(pd.merge(ScimEn_top15_rank, energy, how='inner', on='Country'), GDP[GDP_merge_cols], how='inner', on='Country')
        .set_index('Country')
                 
    )
    
    return merged_dfs

In [6]:
df = answer_one()

In [7]:
df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,472465,470142,6591474,4594673,13.95,380,127191000000,93,19.75491,2.791498e+12,3.604056e+12,4.667346e+12,5.189577e+12,6.192565e+12,7.671757e+12,8.673665e+12,9.743124e+12,1.067453e+13,1.128081e+13
United States,2,222772,217929,4131736,1119917,18.55,491,90838000000,286,11.57098,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,96975,94714,1243636,479638,12.82,258,33195000000,26,14.96908,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
United Kingdom,4,61946,60287,1326766,207337,21.42,313,7920000000,124,10.60047,2.719558e+12,3.104700e+12,2.945252e+12,2.429358e+12,2.496741e+12,2.675590e+12,2.719716e+12,2.796908e+12,3.085362e+12,2.945580e+12
Japan,5,61939,61307,813472,166907,13.13,246,18984000000,149,10.23282,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
Germany,6,55466,54296,932195,185376,16.81,274,13261000000,165,17.90153,3.046309e+12,3.484057e+12,3.808198e+12,3.478546e+12,3.467094e+12,3.823576e+12,3.596483e+12,3.807024e+12,3.964871e+12,3.425100e+12
Russian Federation,7,49938,49562,268391,112125,5.37,123,30709000000,214,17.28868,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,44877,44004,1082361,161133,24.12,305,10431000000,296,61.94543,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,42635,40695,767280,171442,18.00,227,6530000000,109,33.66723,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
South Korea,10,42534,42174,761076,124789,17.89,215,11007000000,221,2.279353,1.095176e+12,1.220912e+12,1.091581e+12,9.830652e+11,1.192830e+12,1.307103e+12,1.335344e+12,1.434670e+12,1.556252e+12,1.539212e+12
Iran,11,35889,35484,798505,211983,22.25,218,9172000000,119,5.707721,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
France,12,33407,32698,637552,99244,19.08,235,10597000000,166,17.02028,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
Spain,13,32521,31781,726414,118758,22.34,233,4923000000,106,37.96859,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
Australia,14,31047,30232,760284,99637,24.49,262,5386000000,231,11.81081,7.497084e+11,8.566036e+11,1.058448e+12,9.317617e+11,1.152567e+12,1.402940e+12,1.552728e+12,1.583737e+12,1.474677e+12,1.356806e+12
Brazil,15,30840,30383,371926,84223,12.06,167,12149000000,59,69.64803,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

In [8]:
df.shape# Розмір (15, 20)

(15, 20)

In [9]:
df.columns # Назви 20 стовпців

Index(['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='str')

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 2
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [10]:
def answer_two():
    ''' Ця функція повертає Series, середнє значення
       ВВП для всіх країн від 2006 до 2015 років '''

    
    Top15 = answer_one()
    years = [str(year) for year in range(2006, 2016)] # list comprehension для років від 2006 до 2015
    
    avgGDP = (Top15[years]
        .dropna()
        .mean(axis=1)
        .sort_values(ascending=False) 
    )
    
    return avgGDP

In [11]:
answer_two()

Country
United States         1.570403e+13
China                 7.048894e+12
Japan                 5.239642e+12
Germany               3.590126e+12
United Kingdom        2.791877e+12
France                2.692000e+12
Italy                 2.152983e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.406644e+12
South Korea           1.275614e+12
Australia             1.211998e+12
Iran                  4.567516e+11
dtype: float64

### Question 3
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [12]:
def answer_three():
    ''' Ця функція повертає чило, яке показу аскільки змінився ВВП
        за 10 років для країни з 6-м за розміром середнім ВВП '''
    
    
    Top15 = (answer_one()
        .assign(mean_GDP=answer_two())
        .sort_values('mean_GDP', ascending=False)
    
    )
    
    res = Top15['2015'].iloc[5] - Top15['2006'].iloc[5]
    return res

In [18]:
answer_three()

np.float64(124621907951.68018)

### Question 4

Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [19]:
def answer_four():
    ''' Ця функція повертає назву країни та найбільше відношення Self-Citations / Total Citations '''

    
    Top15 = answer_one()

    Top15['Self-Citations / Total Citations'] = Top15['Self-citations'] / Top15['Citations']
    index_of_max_ratio = Top15['Self-Citations / Total Citations'].argmax()
    
    return (Top15.iloc[index_of_max_ratio].name, Top15['Self-Citations / Total Citations'].iloc[index_of_max_ratio])

In [20]:
answer_four()

('China', np.float64(0.6970630544852335))

### Question 5

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [21]:
def answer_five():
    Top15 = (answer_one()
        .assign(Population=lambda df_: df_['Energy Supply'] / df_['Energy Supply per Capita'])
    )
   
    country_name = (Top15
        .sort_values('Population', ascending=False)
        .iloc[2].name
    )
    
    return country_name

In [22]:
answer_five()

'United States'

### Question 6
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

In [23]:
def answer_six():
    Top15 = (answer_one()
        .assign(Population=lambda df_: df_['Energy Supply'] / df_['Energy Supply per Capita'])
        .assign(Docs_per_capita=lambda df_: df_['Citable documents'] / df_['Population'])
    )
    
    
    return Top15['Docs_per_capita'].corr(Top15['Energy Supply per Capita'])

In [24]:
answer_six()

np.float64(0.6905473831164103)

### Question 7
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [27]:
def answer_seven():

    ContinentDict  = {'China'             :'Asia', 
                      'United States'     :'North America', 
                      'Japan'             :'Asia', 
                      'United Kingdom'    :'Europe', 
                      'Russian Federation':'Europe', 
                      'Canada'            :'North America', 
                      'Germany'           :'Europe', 
                      'India'             :'Asia',
                      'France'            :'Europe', 
                      'South Korea'       :'Asia', 
                      'Italy'             :'Europe', 
                      'Spain'             :'Europe', 
                      'Iran'              :'Asia',
                      'Australia'         :'Australia', 
                      'Brazil'            :'South America'
    }
    
    Top15 = (answer_one()
            .assign(Population=lambda df_: df_['Energy Supply'] / df_['Energy Supply per Capita'])
    )

    Top15['Continent'] = Top15.index.map(ContinentDict)

    
    return Top15.groupby('Continent')['Population'].agg(['size', 'sum', 'mean', 'std'])

In [30]:
answer_seven()

               size               sum              mean           std
Continent
Asia              5   2898666386.6106   579733277.32212  6.790979e+08
Australia         1   23316017.316017   23316017.316017           NaN
Europe            6  457929667.216372   76321611.202729  3.464767e+07
North America     2   352855249.48025  176427624.740125  1.996696e+08
South America     1  205915254.237288  205915254.237288           NaN

In [31]:
pwd

'C:\\Users\\dimas\\studing\\03-Pandas\\DmytroLutsyk Amazinum Homeworks'